### ISSUE TITLE
Reward Center Security Audit

### ISSUE THREAD

**Issue by kespinola** [holaplex/reward-center-program#7]
## Goal
Remediate all vulnerabilities identified by SolShield for the Reward Center program.

## Tasks
- [ ] Execute Sale
    - buyer reward and seller reward don’t check the owner. Check the buyer and the seller
    - Constraint check on listing.price === offer.price but price from params used for execute_sale. Don’t pass price just reference from the offer.price
-  [ ]On offer update create new buyer trade state. Remove update instruction and go with cancel and re-create.
- [ ] Offer re-init conditions are incorrect. Move to close and recreate both offers and listings.
- [ ] Check the metadata use assert_metadata_valid from metaplex
- [ ] Never pass the price on cancel listing. Always pass in u64 max.
-----
- [ ] Add specs for both the execute sale vulnerabilities
